import { ViroMaterials } from '@reactvision/react-viro';

// Define premium materials with glowing physically-based rendering (PBR) attributes
ViroMaterials.createMaterials({
  neonBlue: {
    diffuseColor: '#00E5FF',
    lightingModel: 'PBR',
    roughness: 0.15,
    metalness: 0.8,
  },
  neonPink: {
    diffuseColor: '#FF007F',
    lightingModel: 'PBR',
    roughness: 0.1,
    metalness: 0.9,
  },
  woodChair: {
    lightingModel: 'Blinn',
  },
  selectionRing: {
    diffuseColor: '#00C2FF',
    lightingModel: 'Constant',
  },
  torchFlame: {
    diffuseColor: '#FF9100',
    diffuseIntensity: 4.0,
    lightingModel: 'Constant',
    bloomThreshold: 0.0,
    blendMode: 'Add',
    cullMode: 'None',
  },
  torchInnerFlame: {
    diffuseColor: '#FFE082',
    diffuseIntensity: 5.0,
    lightingModel: 'Constant',
    bloomThreshold: 0.0,
    blendMode: 'Add',
    cullMode: 'None',
  },
  torchHalo: {
    diffuseColor: '#FFB300',
    diffuseIntensity: 1.8,
    lightingModel: 'Constant',
    bloomThreshold: 0.0,
    blendMode: 'Add',
    cullMode: 'None',
  },
  fireGlow: {
    diffuseColor: '#FFB300',
    diffuseIntensity: 2.5,
    lightingModel: 'Constant',
    bloomThreshold: 0.0,
    blendMode: 'Add',
    cullMode: 'None',
  },
  campfireFlame: {
    diffuseColor: '#FF3D00',
    diffuseIntensity: 4.5,
    lightingModel: 'Constant',
    bloomThreshold: 0.0,
    blendMode: 'Add',
    cullMode: 'None',
  },
  campfireInnerFlame: {
    diffuseColor: '#FFEA00',
    diffuseIntensity: 6.0,
    lightingModel: 'Constant',
    bloomThreshold: 0.0,
    blendMode: 'Add',
    cullMode: 'None',
  },
});

export const DEFAULT_THEME = 'medieval';

// --- PLACEHOLDER MODELS FOR MODERN CITY ---
// These will be replaced once actual models are added to the assets
const PLACEHOLDER_BUILDING = require('../assets/models/cottage.glb');
const PLACEHOLDER_ROAD = require('../assets/models/fence.glb');
const PLACEHOLDER_TRAFFIC = require('../assets/models/lamp.glb');
const PLACEHOLDER_VEHICLE = require('../assets/models/barrel.glb');
const PLACEHOLDER_NATURE = require('../assets/models/bush.glb');
const PLACEHOLDER_UTILITY = require('../assets/models/chair.glb');

export const THEME_CONFIGS = [
  { id: 'medieval', label: 'Medieval World', icon: '🏰' },
  { id: 'modern', label: 'Modern City', icon: '🏙️' },
  { id: 'basic', label: 'Basic Assets', icon: '🧰' },
];

export const THEME_CATEGORY_MAPPINGS = {
  medieval: [
    { id: 'buildings', label: 'Buildings', icon: '🏰' },
    { id: 'nature', label: 'Nature', icon: '🌲' },
    { id: 'decorations', label: 'Decorations', icon: '🪵' },
    { id: 'characters', label: 'Characters', icon: '⚔️' },
    { id: 'custom', label: 'Custom', icon: '📦' },
  ],
  modern: [
    { id: 'buildings', label: 'Buildings', icon: '🏢' },
    { id: 'roads', label: 'Roads', icon: '🛣️' },
    { id: 'traffic', label: 'Traffic', icon: '🚦' },
    { id: 'vehicles', label: 'Vehicles', icon: '🚗' },
    { id: 'nature', label: 'Nature', icon: '🌳' },
    { id: 'utilities', label: 'Utilities', icon: '💡' },
    { id: 'custom', label: 'Custom', icon: '📦' },
  ],
  basic: [
    { id: 'primitives', label: 'Primitives', icon: '✨' },
    { id: 'furniture', label: 'Furniture', icon: '🛋️' },
    { id: 'custom', label: 'Custom', icon: '📦' },
  ],
};

export const getFirstAssetOfTheme = (theme) => {
  const configs = Object.values(MODEL_CONFIGS);
  const match = configs.find(c => c.theme === theme);
  return match ? match.id : null;
};

export const MODEL_CONFIGS = {
  // --- MEDIEVAL THEME MODELS ---
  castle: {
    id: 'castle',
    name: 'Castle',
    category: 'buildings',
    theme: 'medieval',
    thumbnail: '🏰',
    source: require('../assets/models/castle.glb'),
    type: '3d_model',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Castle',
    desc: 'Castle Keep',
    interaction: {
      type: 'torch_glow',
      label: 'Torches',
      icon: '🔥',
    },
  },
  cottage: {
    id: 'cottage',
    name: 'Cottage',
    category: 'buildings',
    theme: 'medieval',
    thumbnail: '🏠',
    source: require('../assets/models/cottage.glb'),
    type: '3d_model',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Cottage',
    desc: 'Cozy House',
  },
  watch_tower: {
    id: 'watch_tower',
    name: 'Watch Tower',
    category: 'buildings',
    theme: 'medieval',
    thumbnail: '🗼',
    source: require('../assets/models/watch_tower.glb'),
    type: '3d_model',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Watch Tower',
    desc: 'Guard Post',
  },
  pine_tree: {
    id: 'pine_tree',
    name: 'Pine Tree',
    category: 'nature',
    theme: 'medieval',
    thumbnail: '🌲',
    source: require('../assets/models/pine_tree.glb'),
    type: '3d_model',
    scale: [1.0, 1.0, 1.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Pine Tree',
    desc: 'Forest Tree',
  },
  bush: {
    id: 'bush',
    name: 'Bush',
    category: 'nature',
    theme: 'medieval',
    thumbnail: '🌳',
    source: require('../assets/models/bush.glb'),
    type: '3d_model',
    scale: [1.0, 1.0, 1.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Bush',
    desc: 'Green Foliage',
  },
  rock: {
    id: 'rock',
    name: 'Rock',
    category: 'nature',
    theme: 'medieval',
    thumbnail: '🪨',
    source: require('../assets/models/rock.glb'),
    type: '3d_model',
    scale: [1.0, 1.0, 1.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Rock',
    desc: 'Large Boulder',
  },
  campfire: {
    id: 'campfire',
    name: 'Campfire',
    category: 'decorations',
    theme: 'medieval',
    thumbnail: '🔥',
    source: require('../assets/models/campfire.glb'),
    type: '3d_model',
    scale: [1.5, 1.5, 1.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Campfire',
    desc: 'Cozy Fire',
    interaction: {
      type: 'fire',
      label: 'Light Campfire',
      icon: '🔥',
    },
  },
  fence: {
    id: 'fence',
    name: 'Fence',
    category: 'decorations',
    theme: 'medieval',
    thumbnail: '🪵',
    source: require('../assets/models/fence.glb'),
    type: '3d_model',
    scale: [1.5, 1.5, 1.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Fence',
    desc: 'Wood Fence',
  },
  barrel: {
    id: 'barrel',
    name: 'Barrel',
    category: 'decorations',
    theme: 'medieval',
    thumbnail: '🛢️',
    source: require('../assets/models/barrel.glb'),
    type: '3d_model',
    scale: [1.5, 1.5, 1.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Barrel',
    desc: 'Wood Barrel',
  },
  knight: {
    id: 'knight',
    name: 'Knight',
    category: 'characters',
    theme: 'medieval',
    thumbnail: '⚔️',
    source: require('../assets/models/knight.glb'),
    type: '3d_model',
    scale: [0.8, 0.8, 0.8],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Knight',
    desc: 'Static Warrior',
    interaction: {
      type: 'aura',
      label: 'Battle Aura',
      icon: '⚡',
    },
  },

  // --- MODERN CITY MODELS (PLACEHOLDERS) ---
  skyscraper: {
    id: 'skyscraper',
    name: 'Skyscraper',
    category: 'buildings',
    theme: 'modern',
    thumbnail: '🏢',
    source: PLACEHOLDER_BUILDING,
    type: '3d_model',
    scale: [0.15, 0.5, 0.15],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Skyscraper',
    desc: 'Placeholder',
  },
  apartment: {
    id: 'apartment',
    name: 'Apartment',
    category: 'buildings',
    theme: 'modern',
    thumbnail: '🏢',
    source: PLACEHOLDER_BUILDING,
    type: '3d_model',
    scale: [0.2, 0.35, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Apartment',
    desc: 'Placeholder',
  },
  shopping_mall: {
    id: 'shopping_mall',
    name: 'Shopping Mall',
    category: 'buildings',
    theme: 'modern',
    thumbnail: '🏬',
    source: PLACEHOLDER_BUILDING,
    type: '3d_model',
    scale: [0.35, 0.2, 0.35],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Shopping Mall',
    desc: 'Placeholder',
  },
  straight_road: {
    id: 'straight_road',
    name: 'Straight Road',
    category: 'roads',
    theme: 'modern',
    thumbnail: '🛣️',
    source: PLACEHOLDER_ROAD,
    type: '3d_model',
    scale: [0.3, 0.01, 0.6],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Straight Road',
    desc: 'Placeholder',
  },
  road_intersection: {
    id: 'road_intersection',
    name: 'Road Intersection',
    category: 'roads',
    theme: 'modern',
    thumbnail: '➕',
    source: PLACEHOLDER_ROAD,
    type: '3d_model',
    scale: [0.6, 0.01, 0.6],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Road Intersection',
    desc: 'Placeholder',
  },
  traffic_light: {
    id: 'traffic_light',
    name: 'Traffic Light',
    category: 'traffic',
    theme: 'modern',
    thumbnail: '🚦',
    source: PLACEHOLDER_TRAFFIC,
    type: '3d_model',
    scale: [0.05, 0.3, 0.05],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Traffic Light',
    desc: 'Placeholder',
  },
  zebra_crossing: {
    id: 'zebra_crossing',
    name: 'Zebra Crossing',
    category: 'traffic',
    theme: 'modern',
    thumbnail: '🏁',
    source: PLACEHOLDER_ROAD,
    type: '3d_model',
    scale: [0.3, 0.01, 0.4],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Zebra Crossing',
    desc: 'Placeholder',
  },
  car: {
    id: 'car',
    name: 'Car',
    category: 'vehicles',
    theme: 'modern',
    thumbnail: '🚗',
    source: PLACEHOLDER_VEHICLE,
    type: '3d_model',
    scale: [0.15, 0.12, 0.25],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Car',
    desc: 'Placeholder',
  },
  bus: {
    id: 'bus',
    name: 'Bus',
    category: 'vehicles',
    theme: 'modern',
    thumbnail: '🚌',
    source: PLACEHOLDER_VEHICLE,
    type: '3d_model',
    scale: [0.18, 0.18, 0.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Bus',
    desc: 'Placeholder',
  },
  modern_tree: {
    id: 'modern_tree',
    name: 'Tree',
    category: 'nature',
    theme: 'modern',
    thumbnail: '🌳',
    source: PLACEHOLDER_NATURE,
    type: '3d_model',
    scale: [0.6, 0.6, 0.6],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Tree',
    desc: 'Placeholder',
  },
  street_light: {
    id: 'street_light',
    name: 'Street Light',
    category: 'utilities',
    theme: 'modern',
    thumbnail: '💡',
    source: PLACEHOLDER_TRAFFIC,
    type: '3d_model',
    scale: [0.05, 0.35, 0.05],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Street Light',
    desc: 'Placeholder',
  },
  bus_stop: {
    id: 'bus_stop',
    name: 'Bus Stop',
    category: 'utilities',
    theme: 'modern',
    thumbnail: '🚏',
    source: PLACEHOLDER_UTILITY,
    type: '3d_model',
    scale: [0.3, 0.3, 0.3],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Bus Stop',
    desc: 'Placeholder',
  },

  // --- BASIC/DEVELOPER THEME MODELS ---
  cube: {
    id: 'cube',
    name: 'Cube',
    category: 'primitives',
    theme: 'basic',
    thumbnail: '□',
    source: null,
    type: 'cube',
    material: 'neonBlue',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.1,
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Cube',
    desc: 'Block',
  },
  sphere: {
    id: 'sphere',
    name: 'Sphere',
    category: 'primitives',
    theme: 'basic',
    thumbnail: '○',
    source: null,
    type: 'sphere',
    material: 'neonPink',
    scale: [0.12, 0.12, 0.12],
    placementYOffset: 0.12,
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Sphere',
    desc: 'Orb',
  },
  chair: {
    id: 'chair',
    name: 'Chair',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '🪑',
    source: require('../assets/models/chair.glb'),
    type: '3d_model',
    scale: [0.4, 0.4, 0.4],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Chair',
    desc: 'Seat',
  },
  table: {
    id: 'table',
    name: 'Table',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '┳',
    source: require('../assets/models/table.glb'),
    type: '3d_model',
    scale: [0.35, 0.35, 0.35],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Table',
    desc: 'Surface',
  },
  lamp: {
    id: 'lamp',
    name: 'Lamp',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '☼',
    source: require('../assets/models/lamp.glb'),
    type: '3d_model',
    scale: [0.02, 0.02, 0.02],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Lamp',
    desc: 'Light',
  },
  plant: {
    id: 'plant',
    name: 'Plant',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '⚘',
    source: require('../assets/models/plant.glb'),
    type: '3d_model',
    scale: [6.0, 6.0, 6.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Plant',
    desc: 'Flora',
  },
};
