import { ViroMaterials } from '@reactvision/react-viro';

// Define premium materials with glowing physically-based rendering (PBR) attributes
ViroMaterials.createMaterials({
  neonBlue: {
    diffuseColor: '#00E5FF',
    lightingModel: 'PBR',
    roughness: 0.15,
    metalness: 0.8,
  },
  neonPink: {
    diffuseColor: '#FF007F',
    lightingModel: 'PBR',
    roughness: 0.1,
    metalness: 0.9,
  },
  woodChair: {
    lightingModel: 'Blinn',
  },
  selectionRing: {
    diffuseColor: '#00C2FF',
    lightingModel: 'Constant',
  },
});

export const CATEGORY_CONFIG = [
  { id: 'shapes', label: 'Shapes', icon: '✨' },
  { id: 'furniture', label: 'Furniture', icon: '🛋️' },
  { id: 'nature', label: 'Nature', icon: '🌲' },
  { id: 'buildings', label: 'Buildings', icon: '🏰' },
  { id: 'vehicles', label: 'Vehicles', icon: '🚗' },
  { id: 'custom', label: 'Custom Assets', icon: '📦' },
];

export const MODEL_CONFIGS = {
  cube: {
    id: 'cube',
    name: 'Cube',
    category: 'shapes',
    theme: 'default',
    thumbnail: '□',
    source: null,
    type: 'cube',
    material: 'neonBlue',
    scale: [0.2, 0.2, 0.2], // 20cm box
    placementYOffset: 0.1, // half of scale Y — sits on plane
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Cube',
    desc: 'Block',
  },
  sphere: {
    id: 'sphere',
    name: 'Sphere',
    category: 'shapes',
    theme: 'default',
    thumbnail: '○',
    source: null,
    type: 'sphere',
    material: 'neonPink',
    scale: [0.12, 0.12, 0.12],
    placementYOffset: 0.12, // radius at scale 1
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Sphere',
    desc: 'Orb',
  },
  chair: {
    id: 'chair',
    name: 'Chair',
    category: 'furniture',
    theme: 'default',
    thumbnail: '🪑',
    source: { uri: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/SheenChair/glTF-Binary/SheenChair.glb' },
    type: '3d_model',
    scale: [0.4, 0.4, 0.4],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Chair',
    desc: 'Seat',
  },
  table: {
    id: 'table',
    name: 'Table',
    category: 'furniture',
    theme: 'default',
    thumbnail: '┳',
    source: { uri: 'https://raw.githubusercontent.com/wass08/meetup-r3f-workshop/main/public/models/table.glb' },
    type: '3d_model',
    scale: [0.35, 0.35, 0.35],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Table',
    desc: 'Surface',
  },
  lamp: {
    id: 'lamp',
    name: 'Lamp',
    category: 'furniture',
    theme: 'default',
    thumbnail: '☼',
    source: { uri: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Lantern/glTF-Binary/Lantern.glb' },
    type: '3d_model',
    scale: [0.02, 0.02, 0.02],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Lamp',
    desc: 'Light',
  },
  plant: {
    id: 'plant',
    name: 'Plant',
    category: 'nature',
    theme: 'default',
    thumbnail: '⚘',
    source: { uri: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF-Binary/Avocado.glb' },
    type: '3d_model',
    scale: [6.0, 6.0, 6.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Plant',
    desc: 'Flora',
  },
};
