import { ViroMaterials } from '@reactvision/react-viro';

// Define premium materials with glowing physically-based rendering (PBR) attributes
ViroMaterials.createMaterials({
  neonBlue: {
    diffuseColor: '#00E5FF',
    lightingModel: 'PBR',
    roughness: 0.15,
    metalness: 0.8,
  },
  neonPink: {
    diffuseColor: '#FF007F',
    lightingModel: 'PBR',
    roughness: 0.1,
    metalness: 0.9,
  },
  woodChair: {
    lightingModel: 'Blinn',
  },
  selectionRing: {
    diffuseColor: '#00C2FF',
    lightingModel: 'Constant',
  },
});

export const DEFAULT_THEME = 'medieval';

export const THEME_CONFIGS = [
  { id: 'medieval', label: 'Medieval', icon: '🏰' },
  { id: 'basic', label: 'Basic Assets', icon: '🔧' },
];

export const THEME_CATEGORY_MAPPINGS = {
  medieval: [
    { id: 'buildings', label: 'Buildings', icon: '🏰' },
    { id: 'nature', label: 'Nature', icon: '🌲' },
    { id: 'furniture', label: 'Decorations', icon: '🔥' },
    { id: 'shapes', label: 'Characters', icon: '⚔️' },
    { id: 'custom', label: 'Custom', icon: '📦' },
  ],
  basic: [
    { id: 'shapes', label: 'Shapes', icon: '✨' },
    { id: 'furniture', label: 'Furniture', icon: '🛋️' },
    { id: 'nature', label: 'Nature', icon: '🌲' },
    { id: 'custom', label: 'Custom', icon: '📦' },
  ],
};

export const getFirstAssetOfTheme = (theme) => {
  const configs = Object.values(MODEL_CONFIGS);
  const match = configs.find(c => c.theme === theme);
  return match ? match.id : null;
};

export const MODEL_CONFIGS = {
  // --- MEDIEVAL THEME MODELS ---
  castle: {
    id: 'castle',
    name: 'Castle',
    category: 'buildings',
    theme: 'medieval',
    thumbnail: '🏰',
    source: require('../assets/models/castle.glb'),
    type: '3d_model',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Castle',
    desc: 'Castle Keep',
  },
  cottage: {
    id: 'cottage',
    name: 'Cottage',
    category: 'buildings',
    theme: 'medieval',
    thumbnail: '🏠',
    source: require('../assets/models/cottage.glb'),
    type: '3d_model',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Cottage',
    desc: 'Cozy House',
  },
  watch_tower: {
    id: 'watch_tower',
    name: 'Watch Tower',
    category: 'buildings',
    theme: 'medieval',
    thumbnail: '🗼',
    source: require('../assets/models/watch_tower.glb'),
    type: '3d_model',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Watch Tower',
    desc: 'Guard Post',
  },
  pine_tree: {
    id: 'pine_tree',
    name: 'Pine Tree',
    category: 'nature',
    theme: 'medieval',
    thumbnail: '🌲',
    source: require('../assets/models/pine_tree.glb'),
    type: '3d_model',
    scale: [1.0, 1.0, 1.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Pine Tree',
    desc: 'Forest Tree',
  },
  bush: {
    id: 'bush',
    name: 'Bush',
    category: 'nature',
    theme: 'medieval',
    thumbnail: '🌳',
    source: require('../assets/models/bush.glb'),
    type: '3d_model',
    scale: [1.0, 1.0, 1.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Bush',
    desc: 'Green Foliage',
  },
  rock: {
    id: 'rock',
    name: 'Rock',
    category: 'nature',
    theme: 'medieval',
    thumbnail: '🪨',
    source: require('../assets/models/rock.glb'),
    type: '3d_model',
    scale: [1.0, 1.0, 1.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Rock',
    desc: 'Large Boulder',
  },
  campfire: {
    id: 'campfire',
    name: 'Campfire',
    category: 'furniture',
    theme: 'medieval',
    thumbnail: '🔥',
    source: require('../assets/models/campfire.glb'),
    type: '3d_model',
    scale: [1.5, 1.5, 1.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Campfire',
    desc: 'Cozy Fire',
  },
  fence: {
    id: 'fence',
    name: 'Fence',
    category: 'furniture',
    theme: 'medieval',
    thumbnail: '🪵',
    source: require('../assets/models/fence.glb'),
    type: '3d_model',
    scale: [1.5, 1.5, 1.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Fence',
    desc: 'Wood Fence',
  },
  barrel: {
    id: 'barrel',
    name: 'Barrel',
    category: 'furniture',
    theme: 'medieval',
    thumbnail: '🛢️',
    source: require('../assets/models/barrel.glb'),
    type: '3d_model',
    scale: [1.5, 1.5, 1.5],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Barrel',
    desc: 'Wood Barrel',
  },
  knight: {
    id: 'knight',
    name: 'Knight',
    category: 'shapes',
    theme: 'medieval',
    thumbnail: '⚔️',
    source: require('../assets/models/knight.glb'),
    type: '3d_model',
    scale: [0.8, 0.8, 0.8],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Knight',
    desc: 'Static Warrior',
  },

  // --- BASIC/DEVELOPER THEME MODELS ---
  cube: {
    id: 'cube',
    name: 'Cube',
    category: 'shapes',
    theme: 'basic',
    thumbnail: '□',
    source: null,
    type: 'cube',
    material: 'neonBlue',
    scale: [0.2, 0.2, 0.2],
    placementYOffset: 0.1,
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Cube',
    desc: 'Block',
  },
  sphere: {
    id: 'sphere',
    name: 'Sphere',
    category: 'shapes',
    theme: 'basic',
    thumbnail: '○',
    source: null,
    type: 'sphere',
    material: 'neonPink',
    scale: [0.12, 0.12, 0.12],
    placementYOffset: 0.12,
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Sphere',
    desc: 'Orb',
  },
  chair: {
    id: 'chair',
    name: 'Chair',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '🪑',
    source: require('../assets/models/chair.glb'),
    type: '3d_model',
    scale: [0.4, 0.4, 0.4],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Chair',
    desc: 'Seat',
  },
  table: {
    id: 'table',
    name: 'Table',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '┳',
    source: require('../assets/models/table.glb'),
    type: '3d_model',
    scale: [0.35, 0.35, 0.35],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Table',
    desc: 'Surface',
  },
  lamp: {
    id: 'lamp',
    name: 'Lamp',
    category: 'furniture',
    theme: 'basic',
    thumbnail: '☼',
    source: require('../assets/models/lamp.glb'),
    type: '3d_model',
    scale: [0.02, 0.02, 0.02],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Lamp',
    desc: 'Light',
  },
  plant: {
    id: 'plant',
    name: 'Plant',
    category: 'nature',
    theme: 'basic',
    thumbnail: '⚘',
    source: require('../assets/models/plant.glb'),
    type: '3d_model',
    scale: [6.0, 6.0, 6.0],
    placementYOffset: 0.0,
    fileFormat: 'GLB',
    supportsInteraction: true,
    supportsRotation: true,
    supportsScaling: true,
    supportsPhysics: false,
    label: 'Plant',
    desc: 'Flora',
  },
};
